pessoas = {'nome': 'Luís', 'sexo': 'M', 'idade': 23}
print(pessoas)
print('-'*30)
print(f'O {pessoas["nome"]} tem {pessoas["idade"]} anos!')
print('-'*30)
print(pessoas.keys())
print('-'*30)
print(pessoas.values())
print('-'*30)
print(pessoas.items())
